<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net$(DotNet_Version)</TargetFramework>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<PropertyGroup Condition="$([System.OperatingSystem]::IsWindows())">
		<TargetFrameworks>net$(DotNet_Version)-windows$(WinSDK_Version)</TargetFrameworks>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="xunit.v3" />
		<PackageReference Include="xunit.runner.visualstudio" />
		<PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Xunit" />
		<Using Include="AigioLTemplate.UnitTest.Abstractions" />
	</ItemGroup>

	<ItemGroup>
		<Compile Include="..\..\ref\serversdk\src\AigioLTemplate.ServerSdk.UnitTest.Shared\Abstractions\*.cs">
			<LinkBase>Abstractions</LinkBase>
		</Compile>
		<Compile Include="..\..\ref\serversdk\src\AigioLTemplate.ServerSdk.UnitTest.Shared\*Test.cs" />
	</ItemGroup>

	<Import Project="..\WindowsForms.props" />

	<Import Project="..\..\ref\serversdk\src\ServerSdk.PackageRef.props" />
	<Import Project="..\..\ref\serversdk\src\AigioLTemplate.ServerSdk.UnitTest.Shared\AigioLTemplate.ServerSdk.UnitTest.Shared.projitems" Label="Shared" />
	<Import Project="..\AigioLTemplate.props" />

</Project>
